schema_version = "1.0.0"

id = "custom_script_manager"
version = "1.0.0"
name = "Custom Script Manager"
tagline = "This is another extension"
maintainer = "maqq1e - github.com/maqq1e"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://github.com/maqq1e/BlenderScriptManager"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Load .json template file"